import type { Metadata } from 'next';
import './styles/globals.css';
import InteractiveForm from './playground/InteractiveForm';
import ComponentsPage from './components/[slug]/component-registry';
import { tokenVariants } from './utils/tokens';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/*
       
        */}
        <div className="flex min-h-screen">
          <aside className="w-64 border-r">
            <ComponentsPage />
          </aside>
          <InteractiveForm tokenVariants={tokenVariants} />
          <main className="flex-1 px-8 py-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
